var first_name="Jay";
var last_name="Metkar";
var full_name=first_name.concat(last_name);
console.log(full_name);
var l_name=full_name.length;
console.log(l_name);
var name_one="i am Jay";
console.log(name_one);
var r_name=name_one.replace("Jay","Metkar");
console.log(r_name);
var cap_name="STARK";
var low_name=cap_name.toLowerCase();
console.log(low_name);
var small_name="tony";
var large_name=small_name.toUpperCase();
console.log(large_name);
var square_root=Math.sqrt(81);
console.log(square_root);
var max_number=Math.max(6,8);
console.log(max_number);
var min_number=Math.min(91,90);
console.log(min_number);
var power_ex=Math.pow(99,4);
console.log(power_ex);